version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${EXTERNAL_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - joke_bot_network

networks:
  joke_bot_network:

volumes:
  db_data: